import java.util.ArrayList;
/**
 * Project 05 -- Amazon Warehouse
 *
 * This program uses classes and interfaces to simulate Amazon.
 *
 * @author Brian Norton, Briana Crowe, lab sec 015
 *
 * @version December 9, 2018
 *
 */

/**
 * <h1>Truck</h1> Represents a Truck
 */
public class Truck extends Vehicle {

    private final double GAS_RATE = 1.66;

    /**
     * Default Constructor
     */
    //============================================================================
    //TODO

    public Truck() {

    }

    //============================================================================

    /**
     * Constructor
     *
     * @param licensePlate license plate of vehicle
     * @param maxWeight    maximum weight that the vehicle can hold
     */
    //============================================================================
    public Truck(String licensePlate, double maxWeight) {
        super(licensePlate, maxWeight);
    }

    //============================================================================

    /*
     * =============================================================================
     * | Methods from Profitable Interface
     * =============================================================================
     */
    /**
     * Returns the profits generated by the packages currently in the Vehicle.
     * <p>
     * &sum;p<sub>price</sub> - (range<sub>max</sub> &times; 1.66)
     * </p>
     */
    @Override
    public double getProfit() {
        double profit = 0;
        for (int i = 0; i < getPackages().size(); i++) {
            Package current = getPackages().get(i);
            double price = current.getPrice();
            profit += price;

        }

        double gasPrice = GAS_RATE * getMaxRange();
        profit -= gasPrice;
        return profit;

    }

    /**
     * Generates a String of the truck report. Truck report includes:
     * <ul>
     * <li>License Plate No.</li>
     * <li>Destination</li>
     * <li>Current Weight/Maximum Weight</li>
     * <li>Net Profit</li>
     * <li>Shipping labels of all packages in truck</li>
     * </ul>
     *
     * @return Truck Report
     */
    @Override
    public String report() {
        String packageLabels = "";

        for (int i = 0; i < getPackages().size(); i++) {
            String thisPackage = getPackages().get(i).shippingLabel();
            packageLabels += thisPackage;

        }
        String report = "==========Cargo Plane Report==========\n" +
                "License Plate No.: " + getLicensePlate() + "\n" +
                "Destination: " + getZipDest() + "\n" +
                "Weight Load: " + getCurrentWeight() + "/" + getMaxWeight() + "\n" +
                "Net Profit: $" + getProfit() + "\n" +
                "=====Shipping Labels=====\n" +
                "====================\n" + packageLabels;

        return report;

    }



}